# Generated by Django 4.2.19 on 2025-03-06 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cv_feedback_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TailoredResumeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tailored_resume', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_description', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cv_feedback_app.jobdescription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
